/**
 * Database schema for `grants` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2025-11-14
 */

export interface GrantSchema {
  created_at: string;
  created_by: string | null;
  description: string | null;
  id: string;
  is_active: boolean;
  month: number;
  name: string;
  updated_at: string;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type GrantInsert = Omit<GrantSchema, 'id' | 'created_at' | 'updated_at'> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type GrantUpdate = {
  id: string;
} & Partial<Omit<GrantSchema, 'id' | 'created_at' | 'updated_at'>>;
