/**
 * Auto-generated API route constants
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by: scripts/generate-api-routes.mjs
 * Generated at: 2025-11-14T14:34:23.454Z
 *
 * To regenerate: npm run generate:api-routes
 */

export const API_ROUTES = {
  admin: {
    updateMaterializedView: '/api/admin/update-materialized-view' as const,
  },
  auth: {
    resetPassword: '/api/auth/reset-password' as const,
    simpleResetPassword: '/api/auth/simple-reset-password' as const,
  },
  blog: {
    root: '/api/blog' as const,
    byId: (id: string | number) => `/api/blog/${id}`,
  },
  categories: {
    feeById: (id: string | number, feeId: string | number) => `/api/categories/${id}/fees/${feeId}`,
    fees: (id: string | number) => `/api/categories/${id}/fees`,
    lineupById: (id: string | number, lineupId: string | number) =>
      `/api/categories/${id}/lineups/${lineupId}`,
    lineupByIdMemberById: (
      id: string | number,
      lineupId: string | number,
      memberId: string | number
    ) => `/api/categories/${id}/lineups/${lineupId}/members/${memberId}`,
    lineupByIdMembers: (id: string | number, lineupId: string | number) =>
      `/api/categories/${id}/lineups/${lineupId}/members`,
    lineups: (id: string | number) => `/api/categories/${id}/lineups`,
  },
  categoryMembershipFees: '/api/category-membership-fees' as const,
  checkUser: '/api/check-user' as const,
  clubConfig: {
    root: '/api/club-config' as const,
    byId: (id: string | number) => `/api/club-config/${id}`,
  },
  clubs: {
    root: '/api/clubs' as const,
    relationships: '/api/clubs/relationships' as const,
    byId: (id: string | number) => `/api/clubs/${id}`,
  },
  comments: {
    root: '/api/comments' as const,
    byId: (id: string | number) => `/api/comments/${id}`,
  },
  dev: {
    extractSchema: '/api/dev/extract-schema' as const,
    testBlogPosts: '/api/dev/test-blog-posts' as const,
    testLoginLog: '/api/dev/test-login-log' as const,
    testMaterializedView: '/api/dev/test-materialized-view' as const,
    testPageVisibility: '/api/dev/test-page-visibility' as const,
  },
  entities: {
    byId: (entity: string | number, id: string | number) => `/api/entities/${entity}/${id}`,
    root: (entity: string | number) => `/api/entities/${entity}`,
  },
  logLogin: '/api/log-login' as const,
  manageUsers: '/api/manage-users' as const,
  matches: {
    lineupById: (id: string | number, lineupId: string | number) =>
      `/api/matches/${id}/lineups/${lineupId}`,
    lineupByIdCoacheById: (
      id: string | number,
      lineupId: string | number,
      coachId: string | number
    ) => `/api/matches/${id}/lineups/${lineupId}/coaches/${coachId}`,
    lineupByIdCoaches: (id: string | number, lineupId: string | number) =>
      `/api/matches/${id}/lineups/${lineupId}/coaches`,
    lineupByIdPlayerById: (
      id: string | number,
      lineupId: string | number,
      playerId: string | number
    ) => `/api/matches/${id}/lineups/${lineupId}/players/${playerId}`,
    lineupByIdPlayers: (id: string | number, lineupId: string | number) =>
      `/api/matches/${id}/lineups/${lineupId}/players`,
    lineups: (id: string | number) => `/api/matches/${id}/lineups`,
  },
  memberFunctions: {
    root: '/api/member-functions' as const,
    byId: (id: string | number) => `/api/member-functions/${id}`,
  },
  memberPayments: '/api/member-payments' as const,
  memberPaymentStatus: '/api/member-payment-status' as const,
  members: {
    root: '/api/members' as const,
    external: '/api/members/external' as const,
    internal: '/api/members/internal' as const,
    membersWithPaymentStatus: '/api/members/members-with-payment-status' as const,
    onLoan: '/api/members/on-loan' as const,
    byId: (id: string | number) => `/api/members/${id}`,
    relationships: (id: string | number) => `/api/members/${id}/relationships`,
  },
  pageVisibility: '/api/page-visibility' as const,
  relationships: {
    byId: (id: string | number) => `/api/relationships/${id}`,
  },
  sponsorship: {
    businessPartners: '/api/sponsorship/business-partners' as const,
    mainPartners: {
      root: '/api/sponsorship/main-partners' as const,
      byId: (id: string | number) => `/api/sponsorship/main-partners/${id}`,
    },
    mediaPartners: '/api/sponsorship/media-partners' as const,
  },
  status: '/api/status' as const,
  todos: {
    root: '/api/todos' as const,
    byId: (id: string | number) => `/api/todos/${id}`,
  },
  userRoles: '/api/user-roles' as const,
  users: '/api/users' as const,
} as const;

/**
 * Type-safe API route constants
 *
 * @example
 * // Static routes
 * fetch(API_ROUTES.status);
 * // => '/api/status'
 *
 * fetch(API_ROUTES.members.internal);
 * // => '/api/members/internal'
 *
 * // Dynamic routes
 * fetch(API_ROUTES.members.byId('123'));
 * // => '/api/members/123'
 *
 * fetch(API_ROUTES.sponsorship.mainPartners.byId('abc'));
 * // => '/api/sponsorship/main-partners/abc'
 */
