/**
 * Auto-generated API route constants
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by: scripts/generate-api-routes.mjs
 * Generated at: 2025-10-22T22:59:18.665Z
 *
 * To regenerate: npm run generate:api-routes
 */

export const API_ROUTES = {
  admin: {
    updateMaterializedView: '/api/admin/update-materialized-view' as const,
  },
  auth: {
    resetPassword: '/api/auth/reset-password' as const,
    simpleResetPassword: '/api/auth/simple-reset-password' as const,
  },
  categories: {
    root: '/api/categories' as const,
    byId: (id: string | number) => `/api/categories/${id}`,
    feeById: (id: string | number, feeId: string | number) => `/api/categories/${id}/fees/${feeId}`,
    fees: (id: string | number) => `/api/categories/${id}/fees`,
  },
  checkUser: '/api/check-user' as const,
  clubConfig: '/api/club-config' as const,
  clubs: {
    root: '/api/clubs' as const,
    relationships: '/api/clubs/relationships' as const,
  },
  dev: {
    extractSchema: '/api/dev/extract-schema' as const,
    testBlogPosts: '/api/dev/test-blog-posts' as const,
    testLoginLog: '/api/dev/test-login-log' as const,
    testMaterializedView: '/api/dev/test-materialized-view' as const,
    testPageVisibility: '/api/dev/test-page-visibility' as const,
  },
  logLogin: '/api/log-login' as const,
  manageUsers: '/api/manage-users' as const,
  memberPayments: '/api/member-payments' as const,
  memberPaymentStatus: '/api/member-payment-status' as const,
  members: {
    root: '/api/members' as const,
    external: '/api/members/external' as const,
    functions: '/api/members/functions' as const,
    internal: '/api/members/internal' as const,
    membersWithPaymentStatus: '/api/members/members-with-payment-status' as const,
    onLoan: '/api/members/on-loan' as const,
    byId: (id: string | number) => `/api/members/${id}`,
    relationships: (id: string | number) => `/api/members/${id}/relationships`,
  },
  pageVisibility: '/api/page-visibility' as const,
  relationships: {
    byId: (id: string | number) => `/api/relationships/${id}`,
  },
  seasons: '/api/seasons' as const,
  sponsorship: {
    businessPartners: '/api/sponsorship/business-partners' as const,
    mainPartners: {
      root: '/api/sponsorship/main-partners' as const,
      byId: (id: string | number) => `/api/sponsorship/main-partners/${id}`,
    },
    mediaPartners: '/api/sponsorship/media-partners' as const,
  },
  status: '/api/status' as const,
  userRoles: '/api/user-roles' as const,
  users: '/api/users' as const,
} as const;

/**
 * Type-safe API route constants
 *
 * @example
 * // Static routes
 * fetch(API_ROUTES.status);
 * // => '/api/status'
 *
 * fetch(API_ROUTES.members.internal);
 * // => '/api/members/internal'
 *
 * // Dynamic routes
 * fetch(API_ROUTES.members.byId('123'));
 * // => '/api/members/123'
 *
 * fetch(API_ROUTES.sponsorship.mainPartners.byId('abc'));
 * // => '/api/sponsorship/main-partners/abc'
 */
