/**
 * Database schema for `tournaments` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-03-11
 */

export interface TournamentsSchema {
  category_id: string | null;
  created_at: string;
  created_by: string | null;
  description: string | null;
  end_date: string | null;
  id: string;
  image_url: string | null;
  name: string;
  post_id: string | null;
  season_id: string | null;
  slug: string;
  start_date: string;
  status: string;
  updated_at: string;
  updated_by: string | null;
  venue: string | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type TournamentsInsert = Omit<TournamentsSchema, 'id' | 'created_at' | 'updated_at'> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type TournamentsUpdate = {
  id: string;
} & Partial<Omit<TournamentsSchema, 'id' | 'created_at' | 'updated_at'>>;
