/**
 * Database schema for `club_categories` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2025-11-20
 */

export interface ClubCategorySchema {
  category_id: string;
  club_id: string;
  created_at: string | null;
  id: string;
  is_active: boolean | null;
  max_teams: number | null;
  season_id: string;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type ClubCategoryInsert = Omit<ClubCategorySchema, 'id' | 'created_at' | 'updated_at'> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type ClubCategoryUpdate = {
  id: string;
} & Partial<Omit<ClubCategorySchema, 'id' | 'created_at' | 'updated_at'>>;
