/**
 * Database schema for `todos` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-01-28
 */

export interface TodoSchema {
  assigned_to: string | null;
  category: string | null;
  created_at: string | null;
  created_by: string | null;
  description: string | null;
  due_date: string | null;
  id: string;
  priority: string | null;
  status: string | null;
  title: string;
  updated_at: string | null;
  user_email: string;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type TodoInsert = Omit<TodoSchema, 'id' | 'created_at' | 'updated_at'> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type TodoUpdate = {
  id: string;
} & Partial<Omit<TodoSchema, 'id' | 'created_at' | 'updated_at'>>;
