/**
 * Database schema for `category_membership_fees` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2025-11-14
 */

export interface CategoryMembershipFeeSchema {
  calendar_year: number;
  category_id: string;
  created_at: string | null;
  created_by: string | null;
  currency: string;
  description: string | null;
  fee_amount: number;
  fee_period: string | null;
  id: string;
  is_active: boolean | null;
  updated_at: string | null;
  updated_by: string | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type CategoryMembershipFeeInsert = Omit<
  CategoryMembershipFeeSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type CategoryMembershipFeeUpdate = {
  id: string;
} & Partial<Omit<CategoryMembershipFeeSchema, 'id' | 'created_at' | 'updated_at'>>;
