/**
 * Database schema for `member_functions` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2025-11-20
 */

export interface MemberFunctionSchema {
  created_at: string | null;
  description: string | null;
  display_name: string;
  id: string;
  is_active: boolean | null;
  name: string;
  sort_order: number | null;
  updated_at: string | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type MemberFunctionInsert = Omit<
  MemberFunctionSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type MemberFunctionUpdate = {
  id: string;
} & Partial<Omit<MemberFunctionSchema, 'id' | 'created_at' | 'updated_at'>>;
