/**
 * Database schema for `point_deductions` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-05-25
 */

export interface PointDeductionSchema {
  id: string;
  team_id: string;
  category_id: string;
  season_id: string;
  points: number;
  reason: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export type PointDeductionInsert = Omit<
  PointDeductionSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string;
};

export type PointDeductionUpdate = {
  id: string;
} & Partial<Omit<PointDeductionSchema, 'id' | 'created_at' | 'updated_at'>>;
