/**
 * Database schema for `role_definitions` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-01-28
 */

export interface RoleDefinitionSchema {
  created_at: string | null;
  description: string | null;
  display_name: string;
  id: string;
  is_active: boolean | null;
  name: string;
  permissions: JSON | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type RoleDefinitionInsert = Omit<
  RoleDefinitionSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type RoleDefinitionUpdate = {
  id: string;
} & Partial<Omit<RoleDefinitionSchema, 'id' | 'created_at' | 'updated_at'>>;
