export enum ActionTypes {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  CANCEL = 'cancel',
  SAVE = 'save',
  CLOSE = 'close',
  APPLY = 'apply',
  RESET = 'reset',
  SEARCH = 'search',
  FILTER = 'filter',
  SORT = 'sort',
  EXPORT = 'export',
  IMPORT = 'import',
  BULK = 'bulk',
  STATUS_TRANSITION = 'status-transition',
  PAYMENT = 'payment',
  PASSWORD_RESET = 'password-reset',
  BLOCKED = 'blocked',
  UNBLOCK = 'unblock',
}
