/**
 * Database schema for `tournament_standings` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-03-11
 */

export interface TournamentStandingsSchema {
  created_at: string;
  created_by: string | null;
  draws: number;
  goals_against: number;
  goals_for: number;
  id: string;
  losses: number;
  matches: number;
  points: number;
  position: number;
  team_id: string | null;
  tournament_id: string;
  updated_at: string;
  updated_by: string | null;
  wins: number;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type TournamentStandingsInsert = Omit<
  TournamentStandingsSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type TournamentStandingsUpdate = {
  id: string;
} & Partial<Omit<TournamentStandingsSchema, 'id' | 'created_at' | 'updated_at'>>;
