/**
 * Database schema for `tournament_teams` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-03-11
 */

export interface TournamentTeamsSchema {
  created_at: string;
  created_by: string | null;
  id: string;
  seed_order: number;
  team_id: string;
  tournament_id: string;
  updated_at: string;
  updated_by: string | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type TournamentTeamsInsert = Omit<
  TournamentTeamsSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type TournamentTeamsUpdate = {
  id: string;
} & Partial<Omit<TournamentTeamsSchema, 'id' | 'created_at' | 'updated_at'>>;
