/**
 * Database schema for `videos` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-01-28
 */

export interface VideoSchema {
  category_id: string;
  club_id: string | null;
  created_at: string | null;
  created_by: string | null;
  description: string | null;
  duration: string | null;
  id: string;
  is_active: boolean | null;
  recording_date: string | null;
  season_id: string | null;
  thumbnail_url: string | null;
  title: string;
  updated_at: string | null;
  updated_by: string | null;
  youtube_id: string;
  youtube_url: string;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type VideoInsert = Omit<VideoSchema, 'id' | 'created_at' | 'updated_at'> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type VideoUpdate = {
  id: string;
} & Partial<Omit<VideoSchema, 'id' | 'created_at' | 'updated_at'>>;
