/**
 * Database schema for `membership_fee_payments` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2025-11-25
 */

export interface MembershipFeePaymentSchema {
  amount: number;
  calendar_year: number;
  category_id: string;
  created_at: string | null;
  created_by: string | null;
  currency: string;
  fee_type: string | null;
  id: string;
  member_id: string;
  notes: string | null;
  payment_date: string;
  payment_method: string | null;
  payment_reference: string | null;
  receipt_number: string | null;
  updated_at: string | null;
  updated_by: string | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type MembershipFeePaymentInsert = Omit<
  MembershipFeePaymentSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type MembershipFeePaymentUpdate = {
  id: string;
} & Partial<Omit<MembershipFeePaymentSchema, 'id' | 'created_at' | 'updated_at'>>;
