/**
 * Database schema for `category_lineup_members` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-02-23
 */

export interface CategoryLineupMemberSchema {
  added_at: string | null;
  added_by: string;
  id: string;
  is_active: boolean | null;
  is_captain: boolean | null;
  is_vice_captain: boolean | null;
  jersey_number: number | null;
  lineup_id: string;
  member_id: string;
  position: string;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type CategoryLineupMemberInsert = Omit<
  CategoryLineupMemberSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type CategoryLineupMemberUpdate = {
  id: string;
} & Partial<Omit<CategoryLineupMemberSchema, 'id' | 'created_at' | 'updated_at'>>;
