// Auto-generated file - do not edit manually
// Generated by: scripts/generate-component-exports.mjs
// Last updated: 2025-09-30T07:42:01.395Z
// Folder: routes

export {default as ProtectedCoachRoute} from './ProtectedCoachRoute';
export {default as ProtectedRoute} from './ProtectedRoute';
