// Auto-generated file - do not edit manually
// Generated by: scripts/generate-component-exports.mjs
// Last updated: 2026-01-16T15:47:47.838Z
// Folder: routes

export {default as ProtectedCoachRoute} from './ProtectedCoachRoute';
export {default as ProtectedRoute} from './ProtectedRoute';
