// Auto-generated file - do not edit manually
// Generated by: scripts/generate-component-exports.mjs
// Last updated: 2025-09-30T12:47:01.543Z
// Folder: routes

export {default as ProtectedCoachRoute} from './ProtectedCoachRoute';
export {default as ProtectedRoute} from './ProtectedRoute';
