/**
 * Database schema for `member_club_relationships` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2025-11-25
 */

export interface MemberClubRelationshipSchema {
  club_id: string;
  created_at: string | null;
  created_by: string | null;
  id: string;
  member_id: string;
  notes: string | null;
  relationship_type: string;
  status: string;
  updated_at: string | null;
  valid_from: string;
  valid_to: string | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type MemberClubRelationshipInsert = Omit<
  MemberClubRelationshipSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type MemberClubRelationshipUpdate = {
  id: string;
} & Partial<Omit<MemberClubRelationshipSchema, 'id' | 'created_at' | 'updated_at'>>;
