/**
 * Database schema for `members_on_loan` view
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2025-11-13
 */

export interface MembersOnLoanSchema {
  category_id: string | null;
  created_at: string | null;
  date_of_birth: string | null;
  functions: string[] | null;
  id: string | null;
  is_active: boolean | null;
  name: string | null;
  notes: string | null;
  origin_club_name: string | null;
  origin_club_short_name: string | null;
  registration_number: string | null;
  relationship_status: string | null;
  relationship_type: string | null;
  sex: string | null;
  surname: string | null;
  updated_at: string | null;
  valid_from: string | null;
  valid_to: string | null;
}
