/**
 * Database schema for `member_attendance` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-01-28
 */

export interface MemberAttendanceSchema {
  attendance_status: string;
  created_at: string | null;
  id: string;
  member_id: string;
  notes: string | null;
  recorded_at: string | null;
  recorded_by: string;
  training_session_id: string;
  updated_at: string | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type MemberAttendanceInsert = Omit<
  MemberAttendanceSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type MemberAttendanceUpdate = {
  id: string;
} & Partial<Omit<MemberAttendanceSchema, 'id' | 'created_at' | 'updated_at'>>;
