/**
 * Database schema for `training_sessions` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-02-23
 */

export interface TrainingSessionSchema {
  category_id: string | null;
  coach_id: string;
  created_at: string | null;
  description: string | null;
  id: string;
  location: string | null;
  season_id: string;
  session_date: string;
  session_time: string | null;
  status: string;
  status_reason: string | null;
  title: string;
  updated_at: string | null;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type TrainingSessionInsert = Omit<
  TrainingSessionSchema,
  'id' | 'created_at' | 'updated_at'
> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type TrainingSessionUpdate = {
  id: string;
} & Partial<Omit<TrainingSessionSchema, 'id' | 'created_at' | 'updated_at'>>;
