// Auto-generated file - do not edit manually
// Generated by: scripts/generate-component-exports.mjs
// Folder: sections

export { AdditionalSection } from './AdditionalSection';
export { BasicInfoSection } from './BasicInfoSection';
export { ContactSection } from './ContactSection';
export { MedicalSection } from './MedicalSection';
export { ParentSection } from './ParentSection';