/**
 * Database schema for `comments` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-01-28
 */

export interface CommentSchema {
  author: string;
  content: string;
  created_at: string | null;
  id: string;
  type: string | null;
  updated_at: string | null;
  user_email: string;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type CommentInsert = Omit<CommentSchema, 'id' | 'created_at' | 'updated_at'> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type CommentUpdate = {
  id: string;
} & Partial<Omit<CommentSchema, 'id' | 'created_at' | 'updated_at'>>;
