// Auto-generated file - do not edit manually
// Generated by: scripts/generate-component-exports.mjs
// Last updated: 2025-10-01T09:17:19.493Z
// Folder: boundaries

export {default as ChunkErrorBoundary} from './ChunkErrorBoundary';
export {default as DatabaseErrorBoundary} from './DatabaseErrorBoundary';
