// Auto-generated file - do not edit manually
// Generated by: scripts/generate-component-exports.mjs
// Last updated: 2025-10-05T21:01:23.231Z
// Folder: boundaries

export {default as ChunkErrorBoundary} from './ChunkErrorBoundary';
export {default as DatabaseErrorBoundary} from './DatabaseErrorBoundary';
