/**
 * Database schema for `referees` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-05-14
 */

export interface RefereeSchema {
  id: string;
  name: string;
  surname: string;
  member_id: string | null;
  is_active: boolean;
  created_at: string | null;
  updated_at: string | null;
}

export type RefereeInsert = Omit<RefereeSchema, 'id' | 'created_at' | 'updated_at'> & {
  id?: string;
};

export type RefereeUpdate = {
  id: string;
} & Partial<Omit<RefereeSchema, 'id' | 'created_at' | 'updated_at'>>;
