export const commonCopy = {
  portal: {
    admin: 'Administrace',
    coach: 'Trenérský portal',
  },
  labels: {
    accessDenied: 'Přístup zamítnut',
    isNotAuthenticated: 'Musíte být přihlášen',
    insufficientRights: 'Nemáte oprávnění pro tento portál',
  },
  actions: {
    add: 'Přidat',
    edit: 'Upravit',
    update: 'Upravit',
    delete: 'Smazat',
    save: 'Uložit',
    cancel: 'Zrušit',
    confirm: 'Potvrdit',
    decline: 'Zamítnout',
    generate: 'Generovat',
    unassign: 'Odebrat',
    assign: 'Přiřadit',
    tryAgain: 'Zkusit znovu',
    search: 'Hledat',
    filter: 'Filtrovat',
    sort: 'Řadit',
    export: 'Exportovat',
    import: 'Importovat',
    bulk: 'Hromadná úprava',
    close: 'Zavřít',
    apply: 'Použít',
    reset: 'Resetovat',
    read: 'Zobrazit',
    statusTransition: 'Změna stavu',
    moveStatusTo: 'Přesunout ze stavu',
    moveStatusFrom: 'do stavu',
    payment: 'Platba',
    create: 'Vytvořit',
    send: 'Odeslat',
    openMenu: 'Otevřít menu',
    openProfile: 'Otevřít profil',
    logout: 'Odhlásit se',
    login: 'Přihlásit se',
    back: 'Zpět',
  },
  alerts: {
    warning: 'Upozornění',
    error: 'Chyba',
    info: 'Informace',
    success: 'Úspěch',
    underConstruction:
      'Tato stránka je v testovacím provozu. Některé funkce mohou být nedostupné nebo nefunkční',
    errorLoadingPage: 'Při načítání stránky došlo k chybě. Zkuste to prosím znovu později.',
  },
  messages: {},
};
