/**
 * Database schema for `coach_cards_with_categories` view
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-02-23
 */

export interface CoachCardsWithCategoriesSchema {
  assigned_categories: string[] | null;
  created_at: string | null;
  email: string | null;
  id: string | null;
  name: string | null;
  note: string | null;
  phone: string | null;
  photo_path: string | null;
  photo_url: string | null;
  published_categories: string[] | null;
  role: string | null;
  surname: string | null;
  updated_at: string | null;
  user_id: string | null;
}
