/**
 * Database schema for `coach_cards` table
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/split-db-types.js
 * Source: src/types/database/supabase.ts
 *
 * To regenerate:
 *   1. Run database migrations
 *   2. Run: npm run generate:types
 *
 * Last generated: 2026-02-23
 */

export interface CoachCardSchema {
  created_at: string | null;
  email: string | null;
  id: string;
  name: string;
  note: string | null;
  phone: string | null;
  photo_path: string | null;
  photo_url: string | null;
  published_categories: string[] | null;
  surname: string;
  updated_at: string | null;
  user_id: string;
}

/**
 * Type for INSERT operations (auto-generated fields excluded)
 */
export type CoachCardInsert = Omit<CoachCardSchema, 'id' | 'created_at' | 'updated_at'> & {
  id?: string; // Optional for inserts
};

/**
 * Type for UPDATE operations (all fields optional except ID)
 */
export type CoachCardUpdate = {
  id: string;
} & Partial<Omit<CoachCardSchema, 'id' | 'created_at' | 'updated_at'>>;
